### ISSUE TITLE
Code herunterladen oder kopieren

### ISSUE THREAD

**Issue by mariopesch** [sensebox/blockly#1]
Da copy to clipboard irgendwie nicht so richtig funktioniert habe ich jetzt den Speichern Button geändert, sodass dort die .ino heruntergeladen werden kann.
Ich würde noch einen zusätzlichen Button zum Speichern der XML(Blöcke) einbauen wie im Bild zu sehen. Hat wer noch nen gutes Icon @felixerdy?
![image](https://user-images.githubusercontent.com/7090577/28138752-2bdbfe66-6752-11e7-81eb-cc5c8aafece2.png)

**Comment by felixerdy** [comment]
Copy to clipboard läuft jetzt dank @mariopesch und icon wurde in #2 hinzugefügt
