### ISSUE TITLE
is this repo still in use?

### ISSUE THREAD

**Issue by noerw** [sensebox/blockly#6]
If not, can this be deleted or at least marked as archived?

I am never sure if this or https://github.com/sensebox/ardublockly-1 is the right version :D

**Comment by mariopesch** [comment]
Yes, this repo is being used to host the blockly version for the old senseBox. I will update the description and add a Readme ;) [https://github.com/sensebox/ardublockly-1](https://github.com/sensebox/ardublockly-1) is the right version for the new senseBox MCU
